### ISSUE TITLE
FastAPI Codebase Structure

### ISSUE THREAD

**Issue by app-generator** [app-generator/fastapi-soft-ui-dashboard#1]
## Proposed Codebase Structure
The project aims to provide a simple, intuitive, and easy-to-extend structure. 

<br /> 

> Hello @barreraalexander - please take a look at this codebase footprint and improve or simplify it. 

The current version is 

<br /> 

```bash
< PROJECT ROOT >
   |-- docs/                            # Folder to contain any helping docs
   |   |-- api_examples.json            # Example doc
   |-- scripts/                         # Folder to contain any SQL scripts
   |   |-- scripts.sql                  # Example script
   |-- src/                             # Folder having all the python code
   |    |-- models                      # Folder having all models
   |       |-- custom/                  # Folder for custom models
   |       |-- db/                      # Folder for database models
   |           |-- product.py           # Example file for the product model
   |           |-- sales.py             # Example file for sales model
   |       |-- request.py               # File containing all request models
   |       |-- response.py              # File containing all response models
   |    |-- routers/                    # Folder for all FastAPI routes
   |       |-- auth/               # Folder for authentication routes
   |           |-- auth_routes.py  # File containing authentication routes 
   |       |-- product_routes.py   # File containing product routes 
   |       |-- sales_routes.py     # File containing sales routes 
   |        |-- healthcheck.py          # Base file for health check for FastAPI
   |    |-- helpers/                    # Folder containing helper methods
   |        |-- product_helpers.py      # File having product related helper methods
   |        |-- sales_helpers.py        # File having sales related helper methods
   |        |-- common_helpers.py       # File having common helper methods
   |        |-- database.py             # File having database connection and methods
   |        |-- cache.py                # File having cache connection and methods
   |        |-- decorators.py           # File having decorators
   |    |-- static/
   |         |-- <css, JS, images>      # CSS files, Javascripts files
   |    |-- templates/                  # Templates used to render pages
   |         |-- includes/              # HTML chunks and components
   |              |-- navigation.html   # Top menu component
   |              |-- sidebar.html      # Sidebar component
   |              |-- footer.html       # App Footer
   |              |-- scripts.html      # Scripts common to all pages
   |         |-- layouts/               # Master pages
   |              |-- base-fullscreen.html  # Used by Authentication pages
   |              |-- base.html         # Used by common pages
   |         |-- accounts/              # Authentication pages
   |              |-- login.html        # Login page
   |              |-- register.html     # Register page
   |         |-- home/                  # UI Kit Pages
   |              |-- index.html        # Index page
   |              |-- 404-page.html     # 404 page
   |              |-- *.html            # All other pages
   |    |-- app.py                      # Containing main method, project startup
   |    |-- config.py                   # Containing Settings class for fetching configurations
   |    |-- constants.py                # Global constants
   |    |-- exception_handlers.py       # Global exception handling
   |
   |-- tests/                           # Folder having tests
   |    |-- __init__.py                 # Containing test startup
   |    |-- test.py              # Containing tests 
   |
   |-- .env.dist                        # Template for environment variables
   |-- .env                             # Actual environment variables file
   |-- .gitignore                       # File containing git ignore configurations                           
   |-- CHANGELOG.md                     # File containing change logs
   |-- LICENSE                          # File containing license information
   |-- Dockerfile                       # Docker file
   |-- Makefile                         # File containing make commands
   |-- README.md                        # README file
   |-- docker-compose.yaml              # File to run docker along with other dependencies
   |-- requirements.txt                 # Python packages dependencies
   |-- package-lock.json                # npm packages information
   |-- package.json                     # npm packages dependencies
   |
   |-- ************************************************************************
```

**Comment by barreraalexander** [comment]
1. So, my overwhelming concern is the mixing of backend and frontend. In my experience, generally the frontend and backend share the same codebase but are hosted on different servers. Indeed, fastapi isn't optimized to serve up templates. For the frontend, if you wanted to keep using python, I would recommend using python FLASK. So the structure would look a little bit like this:

<Project Root>
-- frontend/
     --website/
          --static/ templates/ etc (everything needed for the frontend)

--backend/
     --server/
          --models/ schemas etc (everything needed for the backend)

I didn't write out exactly what would be stored in each folder, as you've outlined it above. 


2. Also, I noticed that there is a scripts folder where sql scripts are going to be stored. I've never really seen raw sql being using with python, most people will go with SQLAlchemy. For the sake of security (sql injection), and just in general scalability, I would recommend we use SQLAlchemy. If you're going to use those scripts to manage the database, I would recommend a module called Alembic.

**Comment by app-generator** [comment]
Hello @barreraalexander 

We need a full FastAPI solution, without mixing Flask in the codebase. 
This product should be a simple monorepo powered by FA. 

Just for reference, please take a look at this Flask project used already in production: 

https://github.com/app-generator/flask-material-kit

Is just a simple codebase that handles the UI using an MVC pattern, without an API node. 

Basically, the current project should be closer to this pattern (no API / UI split). 
Also, being the first iteration, without feedback from users, is a must to keep things ar minimum. 

Let me know your thoughts @barreraalexander.

Ty

**Comment by barreraalexander** [comment]
Absolutely understood! We are going to have front and back served by one server, separated into neat routes as you've outlined above. And then my last question is about mysql and the scripts folder you've created above. Are we going to be writing raw sql or are we going to utilize an ORM like SQLAlchemy? In the case that we use an ORM to interact with the database, we won't be needing a scripts folder, I don't believe. 

I believe lastly, I'd like to go over authentication. We're going to be authenticating using third-party clients like google or twitter? Or are we going to be authenticating on the server, using OAuth and bearers tokens?

**Comment by app-generator** [comment]
Hello @barreraalexander, 

The DB layer should have ORM and Migration library. 

The authentication should be provided in two flavors:

- classic user/pass/email combination (please check the UI for the Flask version)
- Social authentication for `Github` & `Twitter`
  
In the next iteration, an authorization/user roles layer might be added. 
Let's select now the system that will support better this evolution (3rd party tools OR OAuth + bearer tokens). 

Let me know your thoughts on this.   
Ty @barreraalexander

**Comment by barreraalexander** [comment]
Perfect! For the ORM I'll use SQLAlchemy, for the Migration library, I'll use alembic.

As for the classic user authentication, if we're going to use user/email/pass, we're going to be storing user credentials in the database, yes? As in, I'm going to create another table/model?  I'm happy to do it, I just want to make sure we're on the same page :) 

If we're looking for a tool to get started quickly and is easy adapt, I would say let's get started with the classic OAuth + bearer token style. 

I've created a second branch in the git. I'm going to build out the basic tree you've outlined, and be on hold for some of the specifics I've asked above :)

**Comment by app-generator** [comment]
Hello @barreraalexander 

 - yes, all good saving credentials in DB
 - Let's go with OAuth + Bearer Token

Being under development, feel free to commit on the head. 
Once we have a stable version, we can use branches for all future sprints. 

Ty @barreraalexander for your efforts.

**Comment by app-generator** [comment]
P.S. When you have some free time, please update the codebase structure. Ty! 
🚀🚀

**Comment by barreraalexander** [comment]
Got it, just read your message about main, I'll go ahead and merge to main. While I work, I'll be pushing updates every hour or so.

**Comment by app-generator** [comment]
Validated. Closing.
Ty @barreraalexander
