### ISSUE TITLE
SQLite DB - Initial Creation

### ISSUE THREAD

**Issue by app-generator** [app-generator/fastapi-soft-ui-dashboard#9]
Hello @barreraalexander 

The existing SQLite DB was removed - saving binaries on the codebase is not a good practice. 

Please add to this issue the steps a new user should follow in order to generate the SQLite database and the tables. 

Ty!

**Comment by barreraalexander** [comment]
Apologies, I must have committed the .db file before I updated .gitignore. But yes, the original documentation includes the steps on how to create the database, including sqlite.

**Comment by app-generator** [comment]
Valiated. Closing!
Ty @barreraalexander
